const fs = require('fs');
const f = 'apps/web/src/app/dashboard/clients/page.tsx';
let c = fs.readFileSync(f, 'utf8');

// Replace handleAddMaterial (old flat API) with handleAddProduct + handleDeleteProduct + handleAddMaterial (nested) + handleDeleteMaterial (nested)
const oldBlock = [
  '  const handleAddMaterial = async (e: React.FormEvent) => {',
  '    e.preventDefault();',
  '    if (!selectedClient) return;',
  '',
  '    try {',
  '      const res = await fetch(`/api/clients/${selectedClient.id}/materials`, {',
  '        method: "POST",',
  '        headers: { "Content-Type": "application/json" },',
  '        body: JSON.stringify(materialForm),',
  '      });',
  '      const data = await res.json();',
  '',
  '      if (data.error) toast.error("Failed to add material");',
  '      else {',
  '        toast.success("Material added");',
  '        setMaterialForm({ name: "", type: "", default_rate: "" });',
  '        fetchClientDetails(selectedClient);',
  '      }',
  '    } catch (error) {',
  '      toast.error("Failed to add material");',
  '    }',
  '  };',
  '',
  '  const handleDeleteMaterial = async (id: string) => {',
  '    try {',
  '      const res = await fetch(`/api/client-materials/${id}`, {',
  '        method: "DELETE",',
  '      });',
  '      const data = await res.json();',
  '',
  '      if (data.error) toast.error("Failed to delete material");',
  '      else {',
  '        toast.success("Material deleted");',
  '        fetchClientDetails(selectedClient);',
  '      }',
  '    } catch (error) {',
  '      toast.error("Failed to delete material");',
  '    }',
  '  };',
].join('\r\n');

const newBlock = [
  '  const handleAddProduct = async (e: React.FormEvent) => {',
  '    e.preventDefault();',
  '    if (!selectedClient) return;',
  '    try {',
  '      const res = await fetch(`/api/v1/clients/${selectedClient.id}/products`, {',
  '        method: "POST",',
  '        headers: { "Content-Type": "application/json" },',
  '        body: JSON.stringify({ name: productForm.name, defaultRate: Number(productForm.defaultRate) }),',
  '      });',
  '      const data = await res.json();',
  '      if (data.error) toast.error("Failed to add product");',
  '      else {',
  '        toast.success("Product added");',
  '        setProductForm({ name: "", defaultRate: "" });',
  '        fetchClientDetails(selectedClient);',
  '      }',
  '    } catch (error) {',
  '      toast.error("Failed to add product");',
  '    }',
  '  };',
  '',
  '  const handleDeleteProduct = async (productId: string) => {',
  '    if (!selectedClient) return;',
  '    try {',
  '      const res = await fetch(`/api/v1/clients/products/${productId}`, {',
  '        method: "DELETE",',
  '      });',
  '      const data = await res.json();',
  '      if (data.error) toast.error("Failed to delete product");',
  '      else {',
  '        toast.success("Product deleted");',
  '        fetchClientDetails(selectedClient);',
  '      }',
  '    } catch (error) {',
  '      toast.error("Failed to delete product");',
  '    }',
  '  };',
  '',
  '  const handleAddMaterial = async (e: React.FormEvent, productId: string) => {',
  '    e.preventDefault();',
  '    if (!selectedClient) return;',
  '    try {',
  '      const res = await fetch(`/api/v1/clients/${selectedClient.id}/products/${productId}/materials`, {',
  '        method: "POST",',
  '        headers: { "Content-Type": "application/json" },',
  '        body: JSON.stringify({ name: materialForm.name, type: materialForm.type, defaultQty: materialForm.defaultQty || null }),',
  '      });',
  '      const data = await res.json();',
  '      if (data.error) toast.error("Failed to add material");',
  '      else {',
  '        toast.success("Material added");',
  '        setMaterialForm({ productId: "", name: "", type: "", defaultQty: "" });',
  '        fetchMaterialsForProduct(productId);',
  '      }',
  '    } catch (error) {',
  '      toast.error("Failed to add material");',
  '    }',
  '  };',
  '',
  '  const handleDeleteMaterial = async (productId: string, materialId: string) => {',
  '    if (!selectedClient) return;',
  '    try {',
  '      const res = await fetch(`/api/v1/clients/materials/${materialId}`, {',
  '        method: "DELETE",',
  '      });',
  '      const data = await res.json();',
  '      if (data.error) toast.error("Failed to delete material");',
  '      else {',
  '        toast.success("Material deleted");',
  '        fetchMaterialsForProduct(productId);',
  '      }',
  '    } catch (error) {',
  '      toast.error("Failed to delete material");',
  '    }',
  '  };',
].join('\r\n');

if (!c.includes(oldBlock)) {
  console.log('ERROR: old block not found');
  // Debug: show what's around line 280
  const lines = c.split('\n');
  for (let i = 278; i < 320 && i < lines.length; i++) {
    console.log(`${i+1}: ${JSON.stringify(lines[i])}`);
  }
  process.exit(1);
}

c = c.replace(oldBlock, newBlock);
fs.writeFileSync(f, c, 'utf8');
console.log('SUCCESS: handlers replaced');
