import {
  UserPlus,
  MessageCircle,
  CalendarCheck,
  ShoppingBag,
  CheckCircle2,
  Clock3,
  XCircle,
  Truck,
  IndianRupee,
  Receipt,
  CreditCard,
  RotateCcw,
  ClipboardList,
  AlertTriangle,
  CheckCheck,
  Timer,
  UserMinus,
  RefreshCw,
  Fingerprint,
  PackageSearch,
  PackageX,
  PackageCheck,
  ShieldAlert,
  Database,
  ShieldX,
  DownloadCloud,
  Sparkles,
  Bot,
  Bell,
  Package,
  AlertCircle,
  Cpu,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

// ─── Config interface ─────────────────────────────────────────
export interface NotificationIconConfig {
  icon: LucideIcon;
  color: string;        // icon stroke color
  bgLight: string;      // light mode container bg
  bgDark: string;       // dark mode container bg
  borderLight: string;  // light mode border
  borderDark: string;   // dark mode border
  label: string;        // accessibility aria-label
}

// ─── Centralized icon map ─────────────────────────────────────
// Keys must match the actual `notification.type` strings
// used by the NotificationDropdown data generator.
export const notificationIconMap: Record<string, NotificationIconConfig> = {

  // ═══════════════════════════════════════════════════════════
  // ACTIVE IN CODEBASE — these 5 types are generated by
  // NotificationDropdown.tsx data fetching logic
  // ═══════════════════════════════════════════════════════════

  overdue: {
    icon: AlertCircle,
    color: '#DC2626',
    bgLight: 'rgba(220,38,38,0.08)',
    bgDark: 'rgba(239,68,68,0.12)',
    borderLight: 'rgba(220,38,38,0.15)',
    borderDark: 'rgba(239,68,68,0.2)',
    label: 'Order overdue',
  },
  low_stock: {
    icon: PackageSearch,
    color: '#D97706',
    bgLight: 'rgba(217,119,6,0.08)',
    bgDark: 'rgba(245,158,11,0.12)',
    borderLight: 'rgba(217,119,6,0.15)',
    borderDark: 'rgba(245,158,11,0.2)',
    label: 'Low stock',
  },
  payment_pending: {
    icon: IndianRupee,
    color: '#16A34A',
    bgLight: 'rgba(22,163,74,0.08)',
    bgDark: 'rgba(34,197,94,0.12)',
    borderLight: 'rgba(22,163,74,0.15)',
    borderDark: 'rgba(34,197,94,0.2)',
    label: 'Payment pending',
  },
  completed: {
    icon: CheckCircle2,
    color: '#16A34A',
    bgLight: 'rgba(22,163,74,0.08)',
    bgDark: 'rgba(34,197,94,0.12)',
    borderLight: 'rgba(22,163,74,0.15)',
    borderDark: 'rgba(34,197,94,0.2)',
    label: 'Order completed',
  },
  production_stuck: {
    icon: Cpu,
    color: '#7C3AED',
    bgLight: 'rgba(124,58,237,0.08)',
    bgDark: 'rgba(139,92,246,0.12)',
    borderLight: 'rgba(124,58,237,0.15)',
    borderDark: 'rgba(139,92,246,0.2)',
    label: 'Production stuck',
  },

  // ═══════════════════════════════════════════════════════════
  // EXPANSION — future notification types
  // ═══════════════════════════════════════════════════════════

  // ── CLIENT ──────────────────────────────────────
  client_new: {
    icon: UserPlus,
    color: '#2563EB',
    bgLight: 'rgba(37,99,235,0.08)',
    bgDark: 'rgba(59,130,246,0.12)',
    borderLight: 'rgba(37,99,235,0.15)',
    borderDark: 'rgba(59,130,246,0.2)',
    label: 'New client',
  },
  client_overdue: {
    icon: AlertTriangle,
    color: '#EA580C',
    bgLight: 'rgba(234,88,12,0.08)',
    bgDark: 'rgba(251,146,60,0.12)',
    borderLight: 'rgba(234,88,12,0.15)',
    borderDark: 'rgba(251,146,60,0.2)',
    label: 'Client overdue payment',
  },
  client_message: {
    icon: MessageCircle,
    color: '#0891B2',
    bgLight: 'rgba(8,145,178,0.08)',
    bgDark: 'rgba(6,182,212,0.12)',
    borderLight: 'rgba(8,145,178,0.15)',
    borderDark: 'rgba(6,182,212,0.2)',
    label: 'Client message',
  },
  client_meeting: {
    icon: CalendarCheck,
    color: '#7C3AED',
    bgLight: 'rgba(124,58,237,0.08)',
    bgDark: 'rgba(139,92,246,0.12)',
    borderLight: 'rgba(124,58,237,0.15)',
    borderDark: 'rgba(139,92,246,0.2)',
    label: 'Client meeting',
  },

  // ── ORDERS ──────────────────────────────────────
  order_new: {
    icon: ShoppingBag,
    color: '#2563EB',
    bgLight: 'rgba(37,99,235,0.08)',
    bgDark: 'rgba(59,130,246,0.12)',
    borderLight: 'rgba(37,99,235,0.15)',
    borderDark: 'rgba(59,130,246,0.2)',
    label: 'New order',
  },
  order_completed: {
    icon: CheckCircle2,
    color: '#16A34A',
    bgLight: 'rgba(22,163,74,0.08)',
    bgDark: 'rgba(34,197,94,0.12)',
    borderLight: 'rgba(22,163,74,0.15)',
    borderDark: 'rgba(34,197,94,0.2)',
    label: 'Order completed',
  },
  order_delayed: {
    icon: Clock3,
    color: '#D97706',
    bgLight: 'rgba(217,119,6,0.08)',
    bgDark: 'rgba(245,158,11,0.12)',
    borderLight: 'rgba(217,119,6,0.15)',
    borderDark: 'rgba(245,158,11,0.2)',
    label: 'Order delayed',
  },
  order_cancelled: {
    icon: XCircle,
    color: '#DC2626',
    bgLight: 'rgba(220,38,38,0.08)',
    bgDark: 'rgba(239,68,68,0.12)',
    borderLight: 'rgba(220,38,38,0.15)',
    borderDark: 'rgba(239,68,68,0.2)',
    label: 'Order cancelled',
  },
  order_dispatched: {
    icon: Truck,
    color: '#0891B2',
    bgLight: 'rgba(8,145,178,0.08)',
    bgDark: 'rgba(6,182,212,0.12)',
    borderLight: 'rgba(8,145,178,0.15)',
    borderDark: 'rgba(6,182,212,0.2)',
    label: 'Shipment dispatched',
  },

  // ── PAYMENTS / FINANCE ───────────────────────────
  payment_received: {
    icon: IndianRupee,
    color: '#16A34A',
    bgLight: 'rgba(22,163,74,0.08)',
    bgDark: 'rgba(34,197,94,0.12)',
    borderLight: 'rgba(22,163,74,0.15)',
    borderDark: 'rgba(34,197,94,0.2)',
    label: 'Payment received',
  },
  invoice_overdue: {
    icon: Receipt,
    color: '#DC2626',
    bgLight: 'rgba(220,38,38,0.08)',
    bgDark: 'rgba(239,68,68,0.12)',
    borderLight: 'rgba(220,38,38,0.15)',
    borderDark: 'rgba(239,68,68,0.2)',
    label: 'Invoice overdue',
  },
  subscription_expiring: {
    icon: CreditCard,
    color: '#D97706',
    bgLight: 'rgba(217,119,6,0.08)',
    bgDark: 'rgba(245,158,11,0.12)',
    borderLight: 'rgba(217,119,6,0.15)',
    borderDark: 'rgba(245,158,11,0.2)',
    label: 'Subscription expiring',
  },
  refund_issued: {
    icon: RotateCcw,
    color: '#0891B2',
    bgLight: 'rgba(8,145,178,0.08)',
    bgDark: 'rgba(6,182,212,0.12)',
    borderLight: 'rgba(8,145,178,0.15)',
    borderDark: 'rgba(6,182,212,0.2)',
    label: 'Refund issued',
  },

  // ── TASKS ────────────────────────────────────────
  task_assigned: {
    icon: ClipboardList,
    color: '#2563EB',
    bgLight: 'rgba(37,99,235,0.08)',
    bgDark: 'rgba(59,130,246,0.12)',
    borderLight: 'rgba(37,99,235,0.15)',
    borderDark: 'rgba(59,130,246,0.2)',
    label: 'Task assigned',
  },
  task_overdue: {
    icon: AlertTriangle,
    color: '#EA580C',
    bgLight: 'rgba(234,88,12,0.08)',
    bgDark: 'rgba(251,146,60,0.12)',
    borderLight: 'rgba(234,88,12,0.15)',
    borderDark: 'rgba(251,146,60,0.2)',
    label: 'Task overdue',
  },
  task_completed: {
    icon: CheckCheck,
    color: '#16A34A',
    bgLight: 'rgba(22,163,74,0.08)',
    bgDark: 'rgba(34,197,94,0.12)',
    borderLight: 'rgba(22,163,74,0.15)',
    borderDark: 'rgba(34,197,94,0.2)',
    label: 'Task completed',
  },
  task_deadline: {
    icon: Timer,
    color: '#DC2626',
    bgLight: 'rgba(220,38,38,0.08)',
    bgDark: 'rgba(239,68,68,0.12)',
    borderLight: 'rgba(220,38,38,0.15)',
    borderDark: 'rgba(239,68,68,0.2)',
    label: 'Deadline today',
  },

  // ── TEAM ─────────────────────────────────────────
  employee_absent: {
    icon: UserMinus,
    color: '#EA580C',
    bgLight: 'rgba(234,88,12,0.08)',
    bgDark: 'rgba(251,146,60,0.12)',
    borderLight: 'rgba(234,88,12,0.15)',
    borderDark: 'rgba(251,146,60,0.2)',
    label: 'Employee absent',
  },
  employee_joined: {
    icon: UserPlus,
    color: '#16A34A',
    bgLight: 'rgba(22,163,74,0.08)',
    bgDark: 'rgba(34,197,94,0.12)',
    borderLight: 'rgba(22,163,74,0.15)',
    borderDark: 'rgba(34,197,94,0.2)',
    label: 'New employee joined',
  },
  shift_updated: {
    icon: RefreshCw,
    color: '#2563EB',
    bgLight: 'rgba(37,99,235,0.08)',
    bgDark: 'rgba(59,130,246,0.12)',
    borderLight: 'rgba(37,99,235,0.15)',
    borderDark: 'rgba(59,130,246,0.2)',
    label: 'Shift updated',
  },
  attendance_alert: {
    icon: Fingerprint,
    color: '#7C3AED',
    bgLight: 'rgba(124,58,237,0.08)',
    bgDark: 'rgba(139,92,246,0.12)',
    borderLight: 'rgba(124,58,237,0.15)',
    borderDark: 'rgba(139,92,246,0.2)',
    label: 'Attendance alert',
  },

  // ── INVENTORY ────────────────────────────────────
  stock_low: {
    icon: PackageSearch,
    color: '#D97706',
    bgLight: 'rgba(217,119,6,0.08)',
    bgDark: 'rgba(245,158,11,0.12)',
    borderLight: 'rgba(217,119,6,0.15)',
    borderDark: 'rgba(245,158,11,0.2)',
    label: 'Low stock',
  },
  stock_out: {
    icon: PackageX,
    color: '#DC2626',
    bgLight: 'rgba(220,38,38,0.08)',
    bgDark: 'rgba(239,68,68,0.12)',
    borderLight: 'rgba(220,38,38,0.15)',
    borderDark: 'rgba(239,68,68,0.2)',
    label: 'Out of stock',
  },
  stock_restocked: {
    icon: PackageCheck,
    color: '#16A34A',
    bgLight: 'rgba(22,163,74,0.08)',
    bgDark: 'rgba(34,197,94,0.12)',
    borderLight: 'rgba(22,163,74,0.15)',
    borderDark: 'rgba(34,197,94,0.2)',
    label: 'Restocked',
  },

  // ── SYSTEM / SECURITY ────────────────────────────
  login_alert: {
    icon: ShieldAlert,
    color: '#DC2626',
    bgLight: 'rgba(220,38,38,0.08)',
    bgDark: 'rgba(239,68,68,0.12)',
    borderLight: 'rgba(220,38,38,0.15)',
    borderDark: 'rgba(239,68,68,0.2)',
    label: 'Login alert',
  },
  backup_completed: {
    icon: Database,
    color: '#16A34A',
    bgLight: 'rgba(22,163,74,0.08)',
    bgDark: 'rgba(34,197,94,0.12)',
    borderLight: 'rgba(22,163,74,0.15)',
    borderDark: 'rgba(34,197,94,0.2)',
    label: 'Backup completed',
  },
  security_warning: {
    icon: ShieldX,
    color: '#DC2626',
    bgLight: 'rgba(220,38,38,0.08)',
    bgDark: 'rgba(239,68,68,0.12)',
    borderLight: 'rgba(220,38,38,0.15)',
    borderDark: 'rgba(239,68,68,0.2)',
    label: 'Security warning',
  },
  system_update: {
    icon: DownloadCloud,
    color: '#0891B2',
    bgLight: 'rgba(8,145,178,0.08)',
    bgDark: 'rgba(6,182,212,0.12)',
    borderLight: 'rgba(8,145,178,0.15)',
    borderDark: 'rgba(6,182,212,0.2)',
    label: 'System update',
  },

  // ── AI / AUTOMATION ──────────────────────────────
  ai_suggestion: {
    icon: Sparkles,
    color: '#7C3AED',
    bgLight: 'rgba(124,58,237,0.08)',
    bgDark: 'rgba(139,92,246,0.12)',
    borderLight: 'rgba(124,58,237,0.15)',
    borderDark: 'rgba(139,92,246,0.2)',
    label: 'AI suggestion',
  },
  automation_failed: {
    icon: AlertTriangle,
    color: '#DC2626',
    bgLight: 'rgba(220,38,38,0.08)',
    bgDark: 'rgba(239,68,68,0.12)',
    borderLight: 'rgba(220,38,38,0.15)',
    borderDark: 'rgba(239,68,68,0.2)',
    label: 'Automation failed',
  },
  automation_success: {
    icon: Bot,
    color: '#16A34A',
    bgLight: 'rgba(22,163,74,0.08)',
    bgDark: 'rgba(34,197,94,0.12)',
    borderLight: 'rgba(22,163,74,0.15)',
    borderDark: 'rgba(34,197,94,0.2)',
    label: 'Automation success',
  },

  // ── PRODUCTION ───────────────────────────────────
  production_complete: {
    icon: CheckCircle2,
    color: '#16A34A',
    bgLight: 'rgba(22,163,74,0.08)',
    bgDark: 'rgba(34,197,94,0.12)',
    borderLight: 'rgba(22,163,74,0.15)',
    borderDark: 'rgba(34,197,94,0.2)',
    label: 'Production complete',
  },
};

// ─── Fallback for unknown types ───────────────────────────────
export const fallbackIconConfig: NotificationIconConfig = {
  icon: Bell,
  color: '#64748B',
  bgLight: 'rgba(100,116,139,0.08)',
  bgDark: 'rgba(148,163,184,0.12)',
  borderLight: 'rgba(100,116,139,0.15)',
  borderDark: 'rgba(148,163,184,0.2)',
  label: 'Notification',
};

// ─── Lookup helper ────────────────────────────────────────────
export function getNotificationIcon(type: string): NotificationIconConfig {
  return notificationIconMap[type] ?? fallbackIconConfig;
}
