const fs = require('fs');

const createExtras = {
  en: {
    btnContinue: "Continue",
    lblTarget: "Target",
  },
  hi: {
    btnContinue: "जारी रखें",
    lblTarget: "लक्ष्य",
  },
  gu: {
    btnContinue: "ચાલુ રાખો",
    lblTarget: "લક્ષ્ય",
  },
  mr: {
    btnContinue: "पुढे चालू ठेवा",
    lblTarget: "लक्ष्य",
  }
};

const detailExtras = {
  en: {
    tabProgress: "Production Progress",
    tabUpdateProgress: "Update Progress",
    tabDetails: "Production Details",
    tabActivityLog: "Activity Log",
    statEfficiency: "Efficiency",
    statOutputVsTarget: "Output vs target",
    statMaterialUsed: "Material Used",
    statTotalConsumed: "Total consumed",
    statWastage: "Wastage",
    statWastageRate: "% wastage rate",
    statStaffProduced: "Staff produced",
    statProduced: "Produced",
    statRejected: "Rejected",
    lblTarget: "Target",
    lblProgress: "Progress",
    overrideModeTitle: "Admin Override Mode",
    overrideModeDesc: "Turn on to update production progress directly",
    completedNotice: "This production has been completed. No further updates are possible.",
    overrideNotice: "Enable Override Mode above to update production quantities.",
    updateOutputDesc: "Record the current produced and rejected quantities.",
    lblProducedQty: "Produced Quantity",
    lblRejectedQty: "Rejected Quantity",
    errRejectExceedsProduced: "Rejected qty cannot exceed produced qty",
    lblUpdateNotes: "Update Notes (Optional)",
    placeholderUpdateNotes: "Add notes about this progress update...",
    btnSaving: "Saving...",
    btnSaveProgress: "Save Progress",
    secProgressHistory: "Progress History",
    lblProduced: "Produced",
    lblRejected: "Rejected",
    secOrderInfo: "Order Information",
    secProductionSetup: "Production Setup",
    secMaterialsUsed: "Materials Used",
    secSchedule: "Schedule",
    secNotes: "Notes",
    secActivityTimeline: "Activity Timeline",
    noActivityYet: "No activity yet.",
    lblPauseReason: "Reason (Optional)",
    placeholderPauseReason: "e.g. Machine malfunction, Material shortage..."
  },
  hi: {
    tabProgress: "उत्पादन प्रगति",
    tabUpdateProgress: "प्रगति अपडेट करें",
    tabDetails: "उत्पादन विवरण",
    tabActivityLog: "गतिविधि लॉग",
    statEfficiency: "दक्षता",
    statOutputVsTarget: "लक्ष्य के विरुद्ध आउटपुट",
    statMaterialUsed: "प्रयुक्त सामग्री",
    statTotalConsumed: "कुल खपत",
    statWastage: "अपव्यय",
    statWastageRate: "% अपव्यय दर",
    statStaffProduced: "कर्मचारी उत्पादन",
    statProduced: "तैयार",
    statRejected: "अस्वीकृत",
    lblTarget: "लक्ष्य",
    lblProgress: "प्रगति",
    overrideModeTitle: "व्यवस्थापक ओवरराइड मोड",
    overrideModeDesc: "उत्पादन प्रगति को सीधे अपडेट करने के लिए चालू करें",
    completedNotice: "यह उत्पादन पूर्ण हो चुका है। आगे कोई अपडेट संभव नहीं है।",
    overrideNotice: "उत्पादन मात्रा अपडेट करने के लिए ऊपर ओवरराइड मोड सक्षम करें।",
    updateOutputDesc: "वर्तमान में तैयार और अस्वीकृत मात्रा दर्ज करें।",
    lblProducedQty: "तैयार मात्रा",
    lblRejectedQty: "अस्वीकृत मात्रा",
    errRejectExceedsProduced: "अस्वीकृत मात्रा तैयार मात्रा से अधिक नहीं हो सकती",
    lblUpdateNotes: "अपडेट नोट्स (वैकल्पिक)",
    placeholderUpdateNotes: "इस प्रगति अपडेट के बारे में नोट्स जोड़ें...",
    btnSaving: "सहेज रहा है...",
    btnSaveProgress: "प्रगति सहेजें",
    secProgressHistory: "प्रगति इतिहास",
    lblProduced: "तैयार",
    lblRejected: "अस्वीकृत",
    secOrderInfo: "ऑर्डर जानकारी",
    secProductionSetup: "उत्पादन सेटअप",
    secMaterialsUsed: "प्रयुक्त सामग्री",
    secSchedule: "अनुसूची",
    secNotes: "नोट्स",
    secActivityTimeline: "गतिविधि समयरेखा",
    noActivityYet: "अभी तक कोई गतिविधि नहीं।",
    lblPauseReason: "कारण (वैकल्पिक)",
    placeholderPauseReason: "उदा. मशीन में खराबी, सामग्री की कमी..."
  },
  gu: {
    tabProgress: "ઉત્પાદન પ્રગતિ",
    tabUpdateProgress: "પ્રગતિ અપડેટ કરો",
    tabDetails: "ઉત્પાદન વિગતો",
    tabActivityLog: "પ્રવૃત્તિ લોગ",
    statEfficiency: "કાર્યક્ષમતા",
    statOutputVsTarget: "લક્ષ્ય સામે આઉટપુટ",
    statMaterialUsed: "વપરાયેલી સામગ્રી",
    statTotalConsumed: "કુલ વપરાશ",
    statWastage: "બગાડ",
    statWastageRate: "% બગાડ દર",
    statStaffProduced: "સ્ટાફ ઉત્પાદન",
    statProduced: "તૈયાર",
    statRejected: "અસ્વીકાર્ય",
    lblTarget: "લક્ષ્ય",
    lblProgress: "પ્રગતિ",
    overrideModeTitle: "એડમિન ઓવરરાઇડ મોડ",
    overrideModeDesc: "ઉત્પાદન પ્રગતિ સીધી અપડેટ કરવા માટે ચાલુ કરો",
    completedNotice: "આ ઉત્પાદન પૂર્ણ થઈ ગયું છે. આગળ કોઈ સુધારા શક્ય નથી.",
    overrideNotice: "ઉત્પાદન જથ્થો અપડેટ કરવા માટે ઉપર ઓવરરાઇડ મોડ સક્ષમ કરો.",
    updateOutputDesc: "હાલમાં તૈયાર અને અસ્વીકાર્ય જથ્થો નોંધો.",
    lblProducedQty: "તૈયાર જથ્થો",
    lblRejectedQty: "અસ્વીકાર્ય જથ્થો",
    errRejectExceedsProduced: "અસ્વીકાર્ય જથ્થો તૈયાર જથ્થાથી વધુ હોઈ શકે નહીં",
    lblUpdateNotes: "સુધારણા નોંધો (વૈકલ્પિક)",
    placeholderUpdateNotes: "આ પ્રગતિ સુધારણા વિશે નોંધો ઉમેરો...",
    btnSaving: "સાચવી રહ્યું છે...",
    btnSaveProgress: "પ્રગતિ સાચવો",
    secProgressHistory: "પ્રગતિ ઇતિહાસ",
    lblProduced: "તૈયાર",
    lblRejected: "અસ્વીકાર્ય",
    secOrderInfo: "ઓર્ડર માહિતી",
    secProductionSetup: "ઉત્પાદન સેટઅપ",
    secMaterialsUsed: "વપરાયેલી સામગ્રી",
    secSchedule: "સમયપત્રક",
    secNotes: "નોંધો",
    secActivityTimeline: "પ્રવૃત્તિ સમયરેખા",
    noActivityYet: "હજુ સુધી કોઈ પ્રવૃત્તિ નથી.",
    lblPauseReason: "કારણ (વૈકલ્પિક)",
    placeholderPauseReason: "દા.ત. મશીનમાં ખામી, સામગ્રીની અછત..."
  },
  mr: {
    tabProgress: "उत्पादन प्रगती",
    tabUpdateProgress: "प्रगती अपडेट करा",
    tabDetails: "उत्पादन तपशील",
    tabActivityLog: "क्रियाकलाप लॉग",
    statEfficiency: "कार्यक्षमता",
    statOutputVsTarget: "लक्ष्याविरुद्ध आउटपुट",
    statMaterialUsed: "वापरलेले साहित्य",
    statTotalConsumed: "एकूण वापर",
    statWastage: "नासाडी",
    statWastageRate: "% नासाडी दर",
    statStaffProduced: "कर्मचारी उत्पादन",
    statProduced: "तयार",
    statRejected: "नाकारलेले",
    lblTarget: "लक्ष्य",
    lblProgress: "प्रगती",
    overrideModeTitle: "अ‍ॅडमिन ओव्हरराइड मोड",
    overrideModeDesc: "उत्पादन प्रगती थेट अपडेट करण्यासाठी चालू करा",
    completedNotice: "हे उत्पादन पूर्ण झाले आहे. पुढील कोणतेही बदल शक्य नाहीत.",
    overrideNotice: "उत्पादन प्रमाण अपडेट करण्यासाठी वर ओव्हरराइड मोड सक्षम करा.",
    updateOutputDesc: "सध्याचे तयार आणि नाकारलेले प्रमाण नोंदवा.",
    lblProducedQty: "तयार प्रमाण",
    lblRejectedQty: "नाकारलेले प्रमाण",
    errRejectExceedsProduced: "नाकारलेले प्रमाण तयार प्रमाणापेक्षा जास्त असू शकत नाही",
    lblUpdateNotes: "अपडेट टिपा (पर्यायी)",
    placeholderUpdateNotes: "या प्रगती अपडेटबद्दल टिपा जोडा...",
    btnSaving: "सेव्ह करत आहे...",
    btnSaveProgress: "प्रगती सेव्ह करा",
    secProgressHistory: "प्रगती इतिहास",
    lblProduced: "तयार",
    lblRejected: "नाकारलेले",
    secOrderInfo: "ऑर्डर माहिती",
    secProductionSetup: "उत्पादन सेटअप",
    secMaterialsUsed: "वापरलेले साहित्य",
    secSchedule: "वेळापत्रक",
    secNotes: "टिपा",
    secActivityTimeline: "क्रियाकलाप टाइमलाइन",
    noActivityYet: "अद्याप कोणताही क्रियाकलाप नाही.",
    lblPauseReason: "कारण (पर्यायी)",
    placeholderPauseReason: "उदा. मशीनमध्ये बिघाड, साहित्याची कमतरता..."
  }
};

['en', 'hi', 'gu', 'mr'].forEach(loc => {
  const jsonPath = `apps/web/messages/${loc}.json`;
  const data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
  Object.assign(data.production.create, createExtras[loc]);
  Object.assign(data.production.detail, detailExtras[loc]);
  fs.writeFileSync(jsonPath, JSON.stringify(data, null, 2), 'utf8');

  const tsPath = `apps/web/src/messages/${loc}.ts`;
  const tsContent = `// Auto-generated locale messages for ${loc}\nconst messages = ${JSON.stringify(data, null, 2)} as const;\n\nexport default messages;\n`;
  fs.writeFileSync(tsPath, tsContent, 'utf8');
});

console.log('Successfully added all extra keys and compiled to TS!');
